name: Build

# Triggered on all pull requests and pushes to main and develop
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - '**'  # This matches all branch names
  push:
    branches: 
      - main
      - dev

# Permissions needed for PR checks
permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetches all history for all branches and tags

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Cache Next.js build
        uses: actions/cache@v3
        with:
          path: |
            .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Build project
        run: npm run build
        env:
          CI: true

      - name: Run tests
        run: npm test
        env:
          CI: true